/* ============================================================
   SALUS Configurator BETA - Dynamically generated documents
   ------------------------------------------------------------
   Every document is a PLACEHOLDER DOCUMENT: the structure
   expected in production is respected (titles, sections, slots
   for visuals and tables) but the content is fictional and
   clearly marked (watermark + banner). Generated client-side
   with jsPDF from the user's real configuration - the goal is to
   prove the configurator CAN produce documentation (P14, P21).
   ============================================================ */

(function () {
  const CAT = () => globalThis.SALUS_CATALOG;
  const COPY = () => globalThis.SALUS_COPY;

  const NAVY = [29, 40, 88], CYAN = [0, 174, 239], GRAY = [140, 145, 160];
  const M = 16; // margin in mm

  function newDoc() {
    const { jsPDF } = window.jspdf;
    return new jsPDF({ unit: "mm", format: "a4" });
  }

  /* Watermark + BETA banner on the current page */
  function stampBeta(doc) {
    doc.saveGraphicsState && doc.saveGraphicsState();
    doc.setTextColor(225, 232, 245);
    doc.setFontSize(58);
    doc.setFont("helvetica", "bold");
    doc.text("TEST DOCUMENT", 105, 170, { align: "center", angle: 35 });
    doc.setTextColor(0, 0, 0);
    doc.restoreGraphicsState && doc.restoreGraphicsState();
  }

  function header(doc, title, subtitle) {
    stampBeta(doc);
    doc.setFillColor(...NAVY);
    doc.rect(0, 0, 210, 24, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold"); doc.setFontSize(14);
    doc.text("SALUS Controls", M, 10);
    doc.setFont("helvetica", "normal"); doc.setFontSize(10);
    doc.text(title, M, 17);
    doc.setFillColor(...CYAN);
    doc.rect(0, 24, 210, 1.6, "F");
    /* BETA banner */
    doc.setFillColor(255, 244, 214);
    doc.rect(0, 25.6, 210, 8, "F");
    doc.setTextColor(146, 90, 4); doc.setFontSize(8);
    doc.text("BETA BUILD - placeholder document: real structure, fictional content. Not for distribution.", 105, 30.8, { align: "center" });
    if (subtitle) {
      doc.setTextColor(...GRAY); doc.setFontSize(9);
      doc.text(subtitle, M, 40);
    }
    doc.setTextColor(20, 20, 20);
    return subtitle ? 46 : 42;
  }

  function footer(doc, pageLabel) {
    doc.setFontSize(7.5); doc.setTextColor(...GRAY);
    doc.text("Fictional content generated by the Salus BETA configurator - " + new Date().toLocaleDateString("en-GB") + (pageLabel ? "  /  " + pageLabel : ""), 105, 291, { align: "center" });
    doc.setTextColor(20, 20, 20);
  }

  function h2(doc, y, txt) {
    doc.setFillColor(...CYAN); doc.rect(M, y - 3.6, 2, 5, "F");
    doc.setFont("helvetica", "bold"); doc.setFontSize(12); doc.setTextColor(...NAVY);
    doc.text(txt, M + 4, y);
    doc.setFont("helvetica", "normal"); doc.setFontSize(9.5); doc.setTextColor(20, 20, 20);
    return y + 7;
  }

  function para(doc, y, txt, w) {
    const lines = doc.splitTextToSize(txt, w || 178);
    doc.text(lines, M, y);
    return y + lines.length * 4.4 + 2;
  }

  function imgPlaceholder(doc, y, h, label) {
    doc.setDrawColor(...GRAY); doc.setFillColor(243, 247, 252);
    doc.roundedRect(M, y, 178, h, 2, 2, "FD");
    doc.setFontSize(8); doc.setTextColor(...GRAY);
    doc.text("[ Visual: " + label + " ]", 105, y + h / 2, { align: "center" });
    doc.setTextColor(20, 20, 20); doc.setFontSize(9.5);
    return y + h + 5;
  }

  function ensureRoom(doc, y, needed, title) {
    if (y + needed > 280) {
      footer(doc);
      doc.addPage();
      return header(doc, title);
    }
    return y;
  }

  /* ---------- Single installation guide (P21) ----------
     5 sequences in the real order of the job: preparation,
     wiring, pairing, commissioning, functional test. */
  function installGuide(answers, items, meta) {
    const doc = newDoc();
    const agg = window.SalusEngine.aggregate(items);
    const title = "System installation guide - " + (meta.projectCode || "");

    /* Page 1: diagram + list */
    let y = header(doc, title, window.SalusCRM.describeProject(answers));
    y = h2(doc, y + 4, "1. Your system at a glance");
    y = imgPlaceholder(doc, y, 62, "generated system diagram (see the My solution screen)");
    y = h2(doc, y, "Equipment for this installation");
    agg.forEach(it => {
      const p = CAT().products[it.ref] || {};
      doc.setFont("helvetica", "bold");
      doc.text(`${it.qty} × ${p.ref || it.ref}`, M, y);
      doc.setFont("helvetica", "normal");
      doc.text(doc.splitTextToSize(p.name || "", 130), M + 42, y);
      y += 6;
      y = ensureRoom(doc, y, 10, title);
    });
    footer(doc, "Sequence 1/5 - Preparation");

    /* Page 2: preparation + wiring (wired products only) */
    doc.addPage();
    y = header(doc, title);
    y = h2(doc, y + 4, "2. Preparation and checks");
    y = para(doc, y, "Switch off the power at the consumer unit. Check the equipment listed on page 1, the wi-fi coverage near the router, and access to the heat source. [Test content: the real manual will detail the checks product by product.]");
    y = h2(doc, y + 2, "3. Wiring - wired devices only");
    const wired = agg.filter(it => { const p = CAT().products[it.ref] || {}; return p.power === "230v"; });
    if (wired.length === 0) {
      y = para(doc, y, "No wiring: every device in your system is wireless.");
    } else {
      wired.forEach(it => {
        const p = CAT().products[it.ref] || {};
        y = ensureRoom(doc, y, 34, title);
        doc.setFont("helvetica", "bold"); doc.text(p.ref + " - " + p.name, M, y); doc.setFont("helvetica", "normal");
        y += 5;
        y = imgPlaceholder(doc, y, 22, "wiring diagram " + p.ref + " (L, N terminals, contacts)");
      });
    }
    footer(doc, "Sequences 2-3/5 - Preparation & wiring");

    /* Page 3: pairing in order */
    doc.addPage();
    y = header(doc, title);
    y = h2(doc, y + 4, "4. Pairing - in this exact order");
    const order = ["gateway", "wiringCentre", "boilerReceiver", "roomstat", "electricStat", "acController", "trv", "repeater", "relay", "shutterRelay", "windowSensor", "presenceSensor", "standaloneRF", "standaloneWired"];
    let step = 1;
    order.forEach(role => {
      agg.forEach(it => {
        const p = CAT().products[it.ref] || {};
        if (p.role !== role) return;
        y = ensureRoom(doc, y, 16, title);
        doc.setFillColor(...CYAN); doc.circle(M + 3, y - 1.4, 3, "F");
        doc.setTextColor(255, 255, 255); doc.setFontSize(8.5); doc.setFont("helvetica", "bold");
        doc.text(String(step), M + 3, y, { align: "center" });
        doc.setTextColor(20, 20, 20); doc.setFontSize(9.5);
        doc.text(`${p.ref} (${it.qty} × )`, M + 9, y);
        doc.setFont("helvetica", "normal");
        y = para2(doc, y + 4.5, "Hold the pairing button for 5 s, the LED flashes, confirm in the app. [Test content - the real pairing video will be attached to this step.]", M + 9, 165);
        step++;
      });
    });
    footer(doc, "Sequence 4/5 - Pairing");

    /* Page 4: commissioning + final test */
    doc.addPage();
    y = header(doc, title);
    y = h2(doc, y + 4, "5. Commissioning");
    y = para(doc, y, "Name every device after its room (taken from your configuration: " + (answers.rooms || []).map(r => r.name).join(", ") + "). Set the default setpoints suggested by the app. [Test content.]");
    y = h2(doc, y + 2, "6. Final functional test");
    y = para(doc, y, "Raise every thermostat setpoint by +3 C: the heat source (or the matching underfloor loop) must start within 3 minutes. Lower the setpoint again: it must stop. Then test a power cut: every device must re-pair on its own.");
    y = imgPlaceholder(doc, y + 2, 30, "final check table (one line per room)");
    footer(doc, "Sequence 5/5 - Commissioning & test");
    return doc;
  }

  function para2(doc, y, txt, x, w) {
    const lines = doc.splitTextToSize(txt, w);
    doc.text(lines, x, y);
    return y + lines.length * 4.2 + 2.5;
  }

  /* ---------- Quote (P25) ---------- */
  function quote(answers, selection, meta) {
    const doc = newDoc();
    const num = "DEV-BETA-" + (meta.projectCode || "0000").replace(/\D/g, "").padStart(4, "0");
    let y = header(doc, "Quote no. " + num + " - recommended retail prices",
      window.SalusCRM.describeProject(answers));
    doc.setFontSize(8.5); doc.setTextColor(...GRAY);
    doc.text("Single national template - Zoho CRM numbering (simulated in BETA)", M, y); y += 8;
    doc.setTextColor(20, 20, 20);

    /* Line table */
    doc.setFillColor(...NAVY); doc.rect(M, y, 178, 8, "F");
    doc.setTextColor(255, 255, 255); doc.setFontSize(9); doc.setFont("helvetica", "bold");
    doc.text("Reference", M + 2, y + 5.4); doc.text("Description", M + 34, y + 5.4);
    doc.text("Qty", M + 128, y + 5.4); doc.text("Unit*", M + 142, y + 5.4); doc.text("Total*", M + 162, y + 5.4);
    y += 8; doc.setTextColor(20, 20, 20); doc.setFont("helvetica", "normal");
    let total = 0, shade = false;
    (selection.items || []).forEach(it => {
      const p = CAT().products[it.ref] || { name: it.ref, price: 0 };
      if (shade) { doc.setFillColor(245, 249, 253); doc.rect(M, y, 178, 7, "F"); }
      shade = !shade;
      doc.text(p.ref || it.ref, M + 2, y + 5);
      doc.text(doc.splitTextToSize(p.name, 88)[0], M + 34, y + 5);
      doc.text(String(it.qty), M + 128, y + 5);
      doc.text(p.price + " €", M + 142, y + 5);
      doc.text(p.price * it.qty + " €", M + 162, y + 5);
      total += p.price * it.qty;
      y += 7;
      y = ensureRoom(doc, y, 30, "Quote no. " + num);
    });
    doc.setFont("helvetica", "bold"); doc.setFontSize(11);
    doc.setFillColor(...CYAN); doc.rect(M + 108, y + 2, 70, 9, "F");
    doc.setTextColor(255, 255, 255);
    doc.text("Total incl. VAT*: " + total + " €", M + 143, y + 8.2, { align: "center" });
    doc.setTextColor(20, 20, 20); doc.setFont("helvetica", "normal"); doc.setFontSize(9);
    y += 18;
    y = para(doc, y, "* FICTIONAL PRICES - BETA build. Recommended retail prices, indicative, excluding installation. No net price is shown in the tool.");
    if (answers.profile === "installer") {
      doc.setFillColor(235, 246, 255); doc.roundedRect(M, y, 178, 20, 2, 2, "F");
      doc.setFont("helvetica", "bold"); doc.setTextColor(...NAVY);
      doc.text("Installer:", M + 4, y + 7);
      doc.setFont("helvetica", "normal");
      doc.text(doc.splitTextToSize("present this quote to your Salus distributor - " + COPY().distributors.join(", ") + " - to get your trade discount. The exact product codes let them price it without retyping.", 168), M + 4, y + 12);
      y += 26;
    } else {
      y = para(doc, y, "For the installation, Club Pro installers in your area can help (see the My solution screen).");
    }
    doc.setTextColor(20, 20, 20);
    footer(doc);
    return { doc, num, total };
  }

  /* ---------- Placeholder product sheet ---------- */
  function productSheetInto(doc, ref) {
    const p = CAT().products[ref] || { ref, name: "" };
    let y = header(doc, "Product sheet - " + p.ref, p.name);
    y = imgPlaceholder(doc, y + 2, 46, "product photo " + p.ref + " on white background");
    y = h2(doc, y, "What it is for");
    y = para(doc, y, p.solution || "");
    y = h2(doc, y + 1, "Technical specifications");
    const rows = [
      ["Reference", p.ref], ["Protocol", ({ zigbee: "Zigbee 3.0", rf: "RF 868 MHz", wifi: "Wi-Fi", wired: "Wired", none: "-" })[p.protocol] || "-"],
      ["Power supply", p.power === "230v" ? "230 V" : "Batteries / rechargeable"],
      ["Gateway required", p.needsGateway ? "Yes (UG800)" : (p.integratedGateway ? "Built into the receiver" : "No")],
      ["Warranty", "[test data: 5 years]"], ["ErP class", "[test data: " + (p.protocol === "wired" ? "IV" : "VIII") + "]"]
    ];
    rows.forEach(([k, v], i) => {
      if (i % 2 === 0) { doc.setFillColor(245, 249, 253); doc.rect(M, y - 4, 178, 6.4, "F"); }
      doc.setFont("helvetica", "bold"); doc.text(k, M + 2, y);
      doc.setFont("helvetica", "normal"); doc.text(String(v), M + 70, y);
      y += 6.4;
    });
    y = h2(doc, y + 3, "Installation");
    y = para(doc, y, (p.descPro || "") + " [Test content: the real manual will replace this section.]");
    y = imgPlaceholder(doc, y, 26, "wiring / mounting diagram " + p.ref);
    y = h2(doc, y, "Conformity");
    y = para(doc, y, "CE - RED 2014/53/EU. [Placeholder declaration of conformity - test document.]");
    footer(doc);
  }

  function productSheet(ref) {
    const doc = newDoc();
    productSheetInto(doc, ref);
    return doc;
  }

  /* ---------- Full documentation pack (P14) ---------- */
  function docPack(refs, meta) {
    const doc = newDoc();
    let y = header(doc, "Documentation pack - " + (meta.projectCode || ""), "Only the documents for the products in YOUR configuration");
    y = h2(doc, y + 4, "Pack contents");
    refs.forEach(ref => {
      const p = CAT().products[ref] || {};
      doc.setFont("helvetica", "bold"); doc.text(p.ref || ref, M, y); doc.setFont("helvetica", "normal");
      doc.text((p.docs || []).map(d => COPY().docLabels[d]).join(" · "), M + 40, y);
      y += 6; y = ensureRoom(doc, y, 12, "Documentation pack");
    });
    footer(doc, "Contents");
    refs.forEach(ref => { doc.addPage(); productSheetInto(doc, ref); });
    return doc;
  }

  const Docs = { installGuide, quote, productSheet, docPack };
  if (typeof window !== "undefined") window.SalusDocs = Docs;
})();
